CREATE TABLE PROFILE (
    STUDENTID   VARCHAR(20)   NOT NULL,
    NAME        VARCHAR(100)  NOT NULL,
    PROGRAMME   VARCHAR(100)  NOT NULL,
    EMAIL       VARCHAR(100)  NOT NULL,
    HOBBIES     VARCHAR(255)  NOT NULL,
    INTRODUCTION VARCHAR(500) NOT NULL,
    PRIMARY KEY (STUDENTID)
);
